version: '3'
services:
    db:
      build:
        context: ./docker/db
        dockerfile: Dockerfile.db
      container_name: postgresql-plus_v1
      environment:
        - POSTGRES_PASSWORD=123456xxx
        - PGDATA=/var/lib/postgresql/data/pgdata
        - TZ=Asia/Shanghai
        - PGTZ=Asia/Shanghai
      ports:
        - 6688:5432
      volumes:
        - /databases/gpdata/data1/docker/l_search_build/data:/var/lib/postgresql/data
      deploy:
        resources:
          limits:
            memory: 1G

    redis:
      image: redis:alpine
      command: redis-server
      ports:
        - 6689:6379
      deploy:
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 20M

    l_search:
      build:
        context: .
        dockerfile: Dockerfile.main
      depends_on:
        - db
        - redis
      container_name: l_search-main
      environment:
        - LSEARCH_DB_CONNECT_URL=postgresql+psycopg2://postgres:123456xxx@db/l_search
        - REDIS_URL=redis://redis/2
        - LSEARCH_LOGGER_LEVEL=DEBUG
        - EXTRACT_CHUNK_SIZE=50000
        - GEO_CRS_CODE=4549
        - LSEARCH_TIMEZONE=Asia/Shanghai
      ports:
        - 6680:5000
      working_dir: /app
      command: bash -c "python3 manage.py db upgrade && python3 manage.py run --host=0.0.0.0"
      deploy:
        resources:
          limits:
            memory: 512M

    celery_work_1:
      build:
        context: .
        dockerfile: Dockerfile.main
      depends_on:
        - l_search
      container_name: l_search-work-1
      environment:
        - LSEARCH_DB_CONNECT_URL=postgresql+psycopg2://postgres:123456xxx@db/l_search
        - REDIS_URL=redis://redis/2
        - LSEARCH_LOGGER_LEVEL=DEBUG
        - EXTRACT_CHUNK_SIZE=50000
        - GEO_CRS_CODE=4549
        - LSEARCH_TIMEZONE=Asia/Shanghai
      working_dir: /app
      command: bash -c "celery -A l_search.celeryapp.celery_worker.celery worker --concurrency=3 -E"
      deploy:
        resources:
          limits:
            memory: 2G

    celery_beat:
      build:
        context: .
        dockerfile: Dockerfile.main
      depends_on:
        - celery_work_1
      container_name: l_search-schedule
      environment:
        - LSEARCH_DB_CONNECT_URL=postgresql+psycopg2://postgres:123456xxx@db/l_search
        - REDIS_URL=redis://redis/2
        - LSEARCH_LOGGER_LEVEL=DEBUG
        - EXTRACT_CHUNK_SIZE=50000
        - GEO_CRS_CODE=4549
        - LSEARCH_TIMEZONE=Asia/Shanghai
      working_dir: /app
      command: bash -c "celery -A l_search.celeryapp.celery_worker.celery beat"
      deploy:
        resources:
          limits:
            memory: 256M


    flower:
      build:
        context: .
        dockerfile: Dockerfile.main
      depends_on:
        - l_search
      container_name: l_search-work-view
      environment:
        - LSEARCH_DB_CONNECT_URL=postgresql+psycopg2://postgres:123456xxx@db/l_search
        - REDIS_URL=redis://redis/2
        - LSEARCH_LOGGER_LEVEL=DEBUG
        - LSEARCH_TIMEZONE=Asia/Shanghai
      working_dir: /app
      command: bash -c "celery -A l_search.celeryapp.celery_worker.celery flower --port=7789"
      ports:
        - 6681:7789
      deploy:
        resources:
          limits:
            memory: 256M