"""empty message

Revision ID: 1a6a8cf9b4a8
Revises: 5a7e5752e2f7
Create Date: 2021-12-16 21:02:14.140130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a6a8cf9b4a8'
down_revision = '5a7e5752e2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extract_data_info', sa.Column('is_entity', sa.Boolean(), nullable=True))
    op.add_column('extract_data_info', sa.Column('is_full_text_index', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extract_data_info', 'is_full_text_index')
    op.drop_column('extract_data_info', 'is_entity')
    # ### end Alembic commands ###
