"""empty message

Revision ID: 59737570dfda
Revises: 
Create Date: 2021-12-10 15:33:11.806210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59737570dfda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extract_data_info',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('db_object_type', sa.String(length=150), nullable=False),
    sa.Column('db_name', sa.String(length=500), nullable=False),
    sa.Column('table_name', sa.String(length=500), nullable=False),
    sa.Column('table_primary_id', sa.String(length=150), nullable=True),
    sa.Column('table_extract_col', sa.String(length=150), nullable=True),
    sa.Column('latest_table_primary_id', sa.String(length=150), nullable=True),
    sa.Column('latest_extract_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('full_text_index',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('extract_data_info_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=500), nullable=False),
    sa.Column('block_key', sa.String(length=500), nullable=False),
    sa.Column('row_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['extract_data_info_id'], ['extract_data_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TABLE full_text_index ADD FULLTEXT (row_content) WITH PARSER ngram")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('full_text_index')
    op.drop_table('extract_data_info')
    # ### end Alembic commands ###
