"""empty message

Revision ID: 5a7e5752e2f7
Revises: 59737570dfda
Create Date: 2021-12-15 23:05:00.688768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a7e5752e2f7'
down_revision = '59737570dfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_connect_info',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('default_db', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=255), nullable=False),
    sa.Column('pwd', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_metadata_info',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('default_db', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('column_type', sa.String(length=255), nullable=False),
    sa.Column('column_type_length', sa.String(length=255), nullable=False),
    sa.Column('column_comment', sa.String(length=255), nullable=True),
    sa.Column('column_position', sa.Integer(), nullable=False),
    sa.Column('is_extract', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Integer(), nullable=False),
    sa.Column('is_extract_filter', sa.Integer(), nullable=False),
    sa.Column('filter_default', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_metadata_info')
    op.drop_table('db_connect_info')
    # ### end Alembic commands ###
