"""empty message

Revision ID: 71bb193ca893
Revises: 8bb6d95954d6
Create Date: 2022-03-02 15:15:50.379235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bb193ca893'
down_revision = '8bb6d95954d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_info', 'latest_table_primary_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_info', sa.Column('latest_table_primary_id', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
