"""empty message

Revision ID: 8bb6d95954d6
Revises: e3a38c8b2302
Create Date: 2022-03-02 15:10:33.760272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb6d95954d6'
down_revision = 'e3a38c8b2302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_info', 'table_primary_col_is_int')
    op.drop_column('table_info', 'table_primary_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_info', sa.Column('table_primary_col', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('table_info', sa.Column('table_primary_col_is_int', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
