"""empty message

Revision ID: d14525937616
Revises: f73d4f377006
Create Date: 2021-12-01 10:27:08.902005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd14525937616'
down_revision = 'f73d4f377006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_test_index_test',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('full_text_index',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('db_object_type', sa.String(length=150), nullable=False),
    sa.Column('block_name', sa.String(length=500), nullable=False),
    sa.Column('block_key', sa.String(length=500), nullable=False),
    sa.Column('db_name', sa.String(length=500), nullable=False),
    sa.Column('table_name', sa.String(length=500), nullable=False),
    sa.Column('table_primary_id', sa.String(length=150), nullable=False),
    sa.Column('table_extract_col', sa.String(length=150), nullable=False),
    sa.Column('row_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('full_test_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('full_test_index',
    sa.Column('id', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True),
    sa.Column('content', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('full_text_index')
    op.drop_table('full_test_index_test')
    # ### end Alembic commands ###
